### PR TITLE
migrate chaos mesh to the knuu

### LINKED ISSUE #451: Migrate Chaos-mesh to the knuu repo
Currently [chaos-mesh](https://github.com/celestiaorg/knuu-chaos-mesh) is living in another repo and it is being an experimental feature.

This issue suggests that to migrate it to the knuu repo and do more tests on it so we can compare it with [bittwister](https://github.com/celestiaorg/bittwister/) and if it covers everything that bittwister does, we can retire bittwister.

### PR DESCRIPTION
**Pull request by mojtaba-esk**
Closes #451 

it is in draft mode because the tests are flaky, need to find a way to assure the tests always.

The tests are passing when run one by one, but when run altogether some of them fail. The attempts done to mitigate this behavior:
1. Running in sequence
2. Running in individual namespaces (each test has its own knuu object)
3. Added a function to wait until the Chaos rule is applied
4. Added some delay time to make sure the Chaos traffic shape rule is applied & effective
5. Increased the size of the bigfile to download to make the elapsed time measurement more accurate

Even tried to run them separately in different terminals, they also fail when they are running at the same time.

### CODE REVIEW

**Comment by MSevey** [comment]
Can you add it to the github workflow matrix so we can see the failures in CI? 
https://github.com/celestiaorg/knuu/blob/8d1b00fcae71de633bf5236bbec903d4b859303d/.github/workflows/knuu_testing.yml#L14

Can you share what the failures are that you are seeing locally?

**Comment by mojtaba-esk** [comment]
> Can you add it to the github workflow matrix so we can see the failures in CI?

done

> Can you share what the failures are that you are seeing locally?

Sure. Here is when I run it all together with isolated namespaces sequentially:

```sh
=== RUN   TestRunSuite
=== RUN   TestRunSuite/TestBandwidth
time="2024-06-26T10:41:51+02:00" level=info msg="The .env file does not exist, continuing without loading environment variables."
time="2024-06-26T10:41:51+02:00" level=info msg="LOG_LEVEL: info" file="log/logger.go:34"
    suite_setup_test.go:67: Scope: 20240626-104151-940
    chaosmesh_test.go:140: Waiting 10s for chaos mesh to settle
    chaosmesh_test.go:145: Time taken for wget before bandwidth: 27.345988762s 	 after bandwidth: 12.980991868s
    chaosmesh_test.go:147: 
        	Error Trace:	/home/moji/celestia/knuu/e2e/chaosmesh/chaosmesh_test.go:147
        	Error:      	"12.980991868s" is not greater than "27.345988762s"
        	Test:       	TestRunSuite/TestBandwidth
        	Messages:   	Time after bandwidth is not longer than time before bandwidth
=== RUN   TestRunSuite/TestCorrupt
time="2024-06-26T10:42:56+02:00" level=info msg="The .env file does not exist, continuing without loading environment variables."
time="2024-06-26T10:42:56+02:00" level=info msg="LOG_LEVEL: info" file="log/logger.go:34"
    suite_setup_test.go:67: Scope: 20240626-104256-035
    chaosmesh_test.go:108: Waiting 10s for chaos mesh to settle
    chaosmesh_test.go:113: Time taken for wget before corrupt: 29.818175866s 	 after corrupt: 14.994630351s
    chaosmesh_test.go:115: 
        	Error Trace:	/home/moji/celestia/knuu/e2e/chaosmesh/chaosmesh_test.go:115
        	Error:      	"14.994630351s" is not greater than "29.818175866s"
        	Test:       	TestRunSuite/TestCorrupt
        	Messages:   	Time after corrupt is not longer than time before corrupt
=== RUN   TestRunSuite/TestDelay
time="2024-06-26T10:44:04+02:00" level=info msg="The .env file does not exist, continuing without loading environment variables."
time="2024-06-26T10:44:04+02:00" level=info msg="LOG_LEVEL: info" file="log/logger.go:34"
    suite_setup_test.go:67: Scope: 20240626-104404-580
    chaosmesh_test.go:27: Waiting 10s for chaos mesh to settle
    chaosmesh_test.go:32: Time taken for wget before delay: 26.889980033s 	 after delay: 26.170361577s
    chaosmesh_test.go:34: 
        	Error Trace:	/home/moji/celestia/knuu/e2e/chaosmesh/chaosmesh_test.go:34
        	Error:      	"26.170361577s" is not greater than "26.889980033s"
        	Test:       	TestRunSuite/TestDelay
        	Messages:   	Time after delay is not longer than time before delay
=== RUN   TestRunSuite/TestDuplicate
time="2024-06-26T10:45:19+02:00" level=info msg="The .env file does not exist, continuing without loading environment variables."
time="2024-06-26T10:45:19+02:00" level=info msg="LOG_LEVEL: info" file="log/logger.go:34"
    suite_setup_test.go:67: Scope: 20240626-104519-042
    chaosmesh_test.go:81: Waiting 10s for chaos mesh to settle
    chaosmesh_test.go:86: Time taken for wget before duplicate: 27.027887443s 	 after duplicate: 26.465900458s
    chaosmesh_test.go:88: 
        	Error Trace:	/home/moji/celestia/knuu/e2e/chaosmesh/chaosmesh_test.go:88
        	Error:      	"26.465900458s" is not greater than "27.027887443s"
        	Test:       	TestRunSuite/TestDuplicate
        	Messages:   	Time after duplicate is not longer than time before duplicate
=== RUN   TestRunSuite/TestLoss
time="2024-06-26T10:46:42+02:00" level=info msg="The .env file does not exist, continuing without loading environment variables."
time="2024-06-26T10:46:42+02:00" level=info msg="LOG_LEVEL: info" file="log/logger.go:34"
    suite_setup_test.go:67: Scope: 20240626-104642-121
    chaosmesh_test.go:54: Waiting 10s for chaos mesh to settle
    chaosmesh_test.go:59: Time taken for wget before loss: 13.95433273s 	 after loss: 14.305350963s
--- FAIL: TestRunSuite (343.31s)
    --- FAIL: TestRunSuite/TestBandwidth (64.09s)
    --- FAIL: TestRunSuite/TestCorrupt (68.55s)
    --- FAIL: TestRunSuite/TestDelay (74.46s)
    --- FAIL: TestRunSuite/TestDuplicate (83.08s)
    --- PASS: TestRunSuite/TestLoss (53.13s)
FAIL
FAIL	github.com/celestiaorg/knuu/e2e/chaosmesh	343.448s
FAIL
```

and when we run them one by one, they usually pass:

```sh
go test -v ./e2e/chaosmesh/ -timeout 60m -count=1 --run TestRunSuite/TestBandwidth
go test -v ./e2e/chaosmesh/ -timeout 60m -count=1 --run TestRunSuite/TestCorrupt
go test -v ./e2e/chaosmesh/ -timeout 60m -count=1 --run TestRunSuite/TestDelay
go test -v ./e2e/chaosmesh/ -timeout 60m -count=1 --run TestRunSuite/TestDuplicate
go test -v ./e2e/chaosmesh/ -timeout 60m -count=1 --run TestRunSuite/TestLoss
=== RUN   TestRunSuite
=== RUN   TestRunSuite/TestBandwidth
time="2024-06-26T10:54:40+02:00" level=info msg="The .env file does not exist, continuing without loading environment variables."
time="2024-06-26T10:54:40+02:00" level=info msg="LOG_LEVEL: info" file="log/logger.go:34"
    suite_setup_test.go:67: Scope: 20240626-105440-946
    chaosmesh_test.go:140: Waiting 10s for chaos mesh to settle
    chaosmesh_test.go:145: Time taken for wget before bandwidth: 13.117046776s 	 after bandwidth: 27.103344713s
--- PASS: TestRunSuite (65.91s)
    --- PASS: TestRunSuite/TestBandwidth (65.91s)
PASS
ok  	github.com/celestiaorg/knuu/e2e/chaosmesh	66.045s
=== RUN   TestRunSuite
=== RUN   TestRunSuite/TestCorrupt
time="2024-06-26T10:55:49+02:00" level=info msg="The .env file does not exist, continuing without loading environment variables."
time="2024-06-26T10:55:49+02:00" level=info msg="LOG_LEVEL: info" file="log/logger.go:34"
    suite_setup_test.go:67: Scope: 20240626-105549-726
    chaosmesh_test.go:108: Waiting 10s for chaos mesh to settle
    chaosmesh_test.go:113: Time taken for wget before corrupt: 26.214538065s 	 after corrupt: 26.921705398s
--- PASS: TestRunSuite (77.70s)
    --- PASS: TestRunSuite/TestCorrupt (77.70s)
PASS
ok  	github.com/celestiaorg/knuu/e2e/chaosmesh	77.845s
=== RUN   TestRunSuite
=== RUN   TestRunSuite/TestDelay
time="2024-06-26T10:57:10+02:00" level=info msg="The .env file does not exist, continuing without loading environment variables."
time="2024-06-26T10:57:10+02:00" level=info msg="LOG_LEVEL: info" file="log/logger.go:34"
    suite_setup_test.go:67: Scope: 20240626-105710-157
    chaosmesh_test.go:27: Waiting 10s for chaos mesh to settle
    chaosmesh_test.go:32: Time taken for wget before delay: 28.403200834s 	 after delay: 29.653790723s
--- PASS: TestRunSuite (83.11s)
    --- PASS: TestRunSuite/TestDelay (83.11s)
PASS
ok  	github.com/celestiaorg/knuu/e2e/chaosmesh	83.239s
=== RUN   TestRunSuite
=== RUN   TestRunSuite/TestDuplicate
time="2024-06-26T10:58:36+02:00" level=info msg="The .env file does not exist, continuing without loading environment variables."
time="2024-06-26T10:58:36+02:00" level=info msg="LOG_LEVEL: info" file="log/logger.go:34"
    suite_setup_test.go:67: Scope: 20240626-105836-117
    chaosmesh_test.go:81: Waiting 10s for chaos mesh to settle
    chaosmesh_test.go:86: Time taken for wget before duplicate: 14.752317089s 	 after duplicate: 13.546388261s
    chaosmesh_test.go:88: 
        	Error Trace:	/home/moji/celestia/knuu/e2e/chaosmesh/chaosmesh_test.go:88
        	Error:      	"13.546388261s" is not greater than "14.752317089s"
        	Test:       	TestRunSuite/TestDuplicate
        	Messages:   	Time after duplicate is not longer than time before duplicate
--- FAIL: TestRunSuite (52.02s)
    --- FAIL: TestRunSuite/TestDuplicate (52.02s)
FAIL
FAIL	github.com/celestiaorg/knuu/e2e/chaosmesh	52.155s
FAIL
=== RUN   TestRunSuite
=== RUN   TestRunSuite/TestLoss
time="2024-06-26T10:59:30+02:00" level=info msg="The .env file does not exist, continuing without loading environment variables."
time="2024-06-26T10:59:30+02:00" level=info msg="LOG_LEVEL: info" file="log/logger.go:34"
    suite_setup_test.go:67: Scope: 20240626-105930-866
    chaosmesh_test.go:54: Waiting 10s for chaos mesh to settle
    chaosmesh_test.go:59: Time taken for wget before loss: 14.224850495s 	 after loss: 26.397818292s
--- PASS: TestRunSuite (64.47s)
    --- PASS: TestRunSuite/TestLoss (64.47s)
PASS
ok  	github.com/celestiaorg/knuu/e2e/chaosmesh	64.594s
```

**Comment by smuu** [comment]
Can we close this PR?

**Comment by mojtaba-esk** [comment]
> Can we close this PR?
Well if we decide not to use Chaos mesh in knuu, then we can close it.

**Comment by smuu** [comment]
> > Can we close this PR?
> 
> Well if we decide not to use Chaos mesh in knuu, then we can close it.

The teams do not use knuu with network shaping and it seems they will not in the near future.

**Pull request closed without merging**
