### PR TITLE
made changes to the labels

### PR DESCRIPTION
**Pull request by Najamulhassan3383**
## Overview

This pull request aims to update the labels and references in the codebase to reflect the changes made in the `getLabels` function of the `Instance` struct. The updated function now includes the "knuu.sh" prefix in the label keys.

The goal of this change is to ensure consistency and clarity in the labeling scheme used within the codebase. By adding the "knuu.sh" prefix, it clearly indicates that these labels are specific to the "knuu" project.

This PR also includes updates to any references that rely on the previous label format. This ensures that the codebase remains consistent and functions properly with the updated labels.

Resolves https://github.com/celestiaorg/knuu/issues/132

## Checklist

- [x] New and updated code has appropriate documentation
- [x] New and updated code has new and/or updated testing
- [x] Required CI checks are passing
- [ ] Visual proof for any user facing features like CLI or documentation updates
- [ ] Linked issues closed with keywords

Please note that the visual proof and closure of linked issues are not applicable in this specific pull request.

Thank you for considering this pull request.

### CODE REVIEW

**Review by smuu — CHANGES_REQUESTED** [review]
Nice work! Only one small thing: could you also add the prefix here to all the labels mentioned in the issue: https://github.com/celestiaorg/knuu/blob/main/pkg/knuu/instance_helper.go#L59

Thank you for your PR!

**Comment by Najamulhassan3383** [comment]
@smuu I changed all the labels. Can you review it know.

**Comment by smuu** [comment]
@Najamulhassan3383 pls take a look at PR: https://github.com/Najamulhassan3383/knuu/pull/1

**Comment by Najamulhassan3383** [comment]
@smuu 
I wanted to inform you that I have merged your PR into my branch. Thank you for your contributions and the valuable feedback you provided.

Now that the changes from your PR have been incorporated into the codebase, I wanted to ask if there is anything else I should do or if there are any additional steps required from my end. I greatly appreciate your guidance as I am still new to this process.
Please let me know if there are any further actions I need to take or if you have any additional suggestions or feedback.
Thank you once again for your assistance and support.
Best regards,

**Review by smuu — APPROVED** [review]
@Najamulhassan3383 I'm sorry for the delay.

Thank you for your great first contribution :rocket: Feel free to grab another issue if you want :raised_hands:

**Pull request merged**
